version: "3.8"

services:
  server:
    build: server
    ports:
      - "5000:5000"
    volumes:
      - servervol:/serverdata

  client:
    build: client
    ports:
      - "8000:8000"
    volumes:
      - clientvol:/clientdata

volumes:
  servervol:
  clientvol: