global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
      - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - 54.236.218.136:9090 # localhost to 123.123.123.1:9090
  - job_name: elzim # Change to whatever you like
    static_configs:
      - targets: ['54.236.218.136:9100'] #Change this to your server's IP